-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 18:32:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskmanager_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskmanager_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskmanager_db` DEFAULT CHARACTER SET utf8 ;
USE `taskmanager_db` ;

-- -----------------------------------------------------
-- Table `taskmanager_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanager_db`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nickname` NVARCHAR(45) NOT NULL,
  `password` NVARCHAR(45) NOT NULL,
  `fullname` MEDIUMTEXT NULL,
  `email` NVARCHAR(100) NULL,
  `phone` NVARCHAR(45) NULL,
  `status` ENUM('deleted', 'active') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskmanager_db`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanager_db`.`service` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(100) NULL,
  `parent` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_FK_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `parent_FK`
    FOREIGN KEY (`parent`)
    REFERENCES `taskmanager_db`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskmanager_db`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanager_db`.`task` (
  `id` BIGINT NOT NULL,
  `name` NVARCHAR(255) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `execution_date` DATETIME NULL,
  `status` ENUM('new', 'completed', 'on_execution') NOT NULL,
  `address` NVARCHAR(255) NULL,
  `file` NVARCHAR(255) NULL,
  `description` NVARCHAR(1024) NULL,
  `customer` BIGINT NOT NULL,
  `executor` BIGINT NULL,
  `service` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_FK_idx` (`customer` ASC) VISIBLE,
  INDEX `executor_FK_idx` (`executor` ASC) VISIBLE,
  INDEX `service_FK_idx` (`service` ASC) VISIBLE,
  CONSTRAINT `customer_FK`
    FOREIGN KEY (`customer`)
    REFERENCES `taskmanager_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `executor_FK`
    FOREIGN KEY (`executor`)
    REFERENCES `taskmanager_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_FK`
    FOREIGN KEY (`service`)
    REFERENCES `taskmanager_db`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskmanager_db`.`user_has_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanager_db`.`user_has_service` (
  `user` BIGINT NOT NULL,
  `service` BIGINT NOT NULL,
  INDEX `fk_user_has_service_service1_idx` (`service` ASC) VISIBLE,
  INDEX `fk_user_has_service_user1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_service_user1`
    FOREIGN KEY (`user`)
    REFERENCES `taskmanager_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_service_service1`
    FOREIGN KEY (`service`)
    REFERENCES `taskmanager_db`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
